name: Hello GA
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      COURSE: CloudComputing
    steps:
      - name: Say Hello
        run: echo "Hello from ${COURSE}!"
      - run: echo "Iâ€™ll list files."
      - run: ls -al
